# Generated by Django 4.0.2 on 2022-06-04 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('sitename', models.CharField(max_length=100)),
                ('siteaddress', models.CharField(max_length=200)),
                ('utillityname', models.CharField(max_length=45)),
                ('category', models.CharField(blank=True, max_length=45)),
                ('emailaddress', models.CharField(max_length=45)),
                ('contact_name', models.CharField(max_length=45)),
                ('phone_no', models.BigIntegerField(null=True)),
                ('sitetype', models.CharField(blank=True, max_length=45)),
                ('pvdesc', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Company_load_data',
            fields=[
                ('DataID', models.AutoField(primary_key=True, serialize=False)),
                ('usage_point', models.CharField(blank=True, max_length=45)),
                ('loaddata', models.FileField(upload_to='load-files')),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Predicted_csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_and_time', models.DateTimeField()),
                ('Usage', models.FloatField()),
                ('Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company_resiliency_details',
            fields=[
                ('resiliencyID', models.AutoField(primary_key=True, serialize=False)),
                ('criticalload', models.CharField(blank=True, max_length=50)),
                ('noofoutages', models.CharField(blank=True, max_length=50)),
                ('outageduration', models.CharField(blank=True, max_length=50)),
                ('outageType', models.CharField(blank=True, max_length=50)),
                ('othertype', models.CharField(blank=True, max_length=50)),
                ('powerfailureimpact', models.CharField(blank=True, max_length=500)),
                ('companyid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='resiliency_data', to='companys.company')),
            ],
        ),
        migrations.CreateModel(
            name='Company_new_ev_details',
            fields=[
                ('NewEvID', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_req_evchargers', models.IntegerField()),
                ('charger_type', models.CharField(max_length=50)),
                ('EVcharge', models.CharField(max_length=50)),
                ('visiting_vehicles', models.CharField(max_length=50)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_ev', to='companys.company')),
            ],
        ),
        migrations.CreateModel(
            name='Company_existing_pv_data',
            fields=[
                ('PvID', models.AutoField(primary_key=True, serialize=False)),
                ('existingpvsize', models.IntegerField()),
                ('existingpvtype', models.CharField(max_length=45)),
                ('solarGenerationdata', models.FileField(null=True, upload_to='Solar-generation')),
                ('systemSLD', models.FileField(null=True, upload_to='system-SLD')),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existing_pv_data', to='companys.company')),
            ],
        ),
        migrations.CreateModel(
            name='Company_existing_ev_data',
            fields=[
                ('EvID', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_existingevs', models.CharField(max_length=50)),
                ('no_of_existingevchargers', models.IntegerField()),
                ('existingevdesc', models.CharField(max_length=500)),
                ('annual_ev_miles', models.IntegerField()),
                ('annual_fuel_expenditure', models.IntegerField()),
                ('desired_ev_details', models.CharField(max_length=500)),
                ('additionalInformation', models.CharField(max_length=500)),
                ('no_of_req_evchargers', models.IntegerField()),
                ('charger_type', models.CharField(max_length=50)),
                ('EVcharge', models.CharField(max_length=50)),
                ('companyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existing_ev_data', to='companys.company')),
            ],
        ),
    ]
